services:
  - type: web
    name: client-app
    env: docker
    docker:
      image: ghcr.io/develmts/client-app:prod
    region: frankfurt    # o eu-central, dep√®n del que Render admeti / et convingui
    plan: starter        # o free / standard / etc, segons el que trieu
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
    healthCheckPath: /health   # canvia-ho o elimina-ho segons la teva app
    autoDeploy: true
